apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranga-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ranga
  template:
    metadata:
      labels:
        app: ranga
    spec:
      containers:
        - name: ranga
          image: yourdockerhub/demo:latest   # ðŸ‘ˆ Jenkins will update tag
          ports:
            - containerPort: 80
