apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranga-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ranga
  template:
    metadata:
      labels:
        app: ranga
    spec:
      containers:
      - name: ranga
        image: nginx
        ports:
        - containerPort: 80

